### ISSUE TITLE
Remove userName field

### ISSUE THREAD

**Issue by jonggietechie** [NUS-ISS-Projects/bit-scout-user-service#1]
Create a an account will only need Full name, email and password
![image](https://github.com/user-attachments/assets/2a3bbbeb-4c4a-4422-8a37-c521b97364b6)

For login, we will just use the email.
![image](https://github.com/user-attachments/assets/e1d667c2-fd7e-4868-97b6-824ff074cb75)

**Comment by OngJiaYuan** [comment]
removed
