### ISSUE TITLE
Update User Details Controller

### ISSUE THREAD

**Issue by jonggietechie** [NUS-ISS-Projects/bit-scout-user-service#2]
We need an endpoint for the user to update their details:
![image](https://github.com/user-attachments/assets/11959d42-622a-405c-a364-265f5038c63e)

**Comment by OngJiaYuan** [comment]
removed username

{
    "uid": "tLUsR8vZfVegLS1OtksV77Vl22G3",
    "email": "johndoe2@example.com",
    "password": "password1234",
    "name": "John Doe",
    "avatar": "https://example.com/avatar.jpg",
    "introduction": "Hi, I'm John Doe."
}

**Comment by OngJiaYuan** [comment]
http://localhost:8081/account/user/updateUser



body 

{
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjExYzhiMmRmNGM1NTlkMjhjOWRlNWQ0MTAxNDFiMzBkOWUyYmNlM2IiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYml0LXNjb3V0LTdiYzA4IiwiYXVkIjoiYml0LXNjb3V0LTdiYzA4IiwiYXV0aF90aW1lIjoxNzI0OTQyMTcwLCJ1c2VyX2lkIjoibTJIcTM3Z2d4M085dTEweElGclEzTXliNGJyMiIsInN1YiI6Im0ySHEzN2dneDNPOXUxMHhJRnJRM015YjRicjIiLCJpYXQiOjE3MjQ5NDIxNzAsImV4cCI6MTcyNDk0NTc3MCwiZW1haWwiOiJqb2huZG9lMzJAZXhhbXBsZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiam9obmRvZTMyQGV4YW1wbGUuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.MDqQpG56j5IUVXQ6ncCJOM5WQ3jdPMRU21grjAiKKKLbEplM9nVfrA6rq7L61PBRO9iiQ0YjP6dHzUtK-EvbSJCKsDxOMRM30RS3LsOw5bBgBL14Zj5PqYJjm0IgX2IldtmRCG4ofwBvaGwBHxuX8mRew8TVWf1k6R1sV1lFso4SjPaoTtB3wykHikzDMmLhKZuhodh3WqukKZz4PuZ_HhAcopEyWkNrBxk5f_QaPvXirGBFG-UGS4ftmy5vfwEj-8xciu9dzjmiWGcntZ7AssIWPC3XfFO5idt8G1M32ksNo8awWUCsp7JaVwWHRq0QzONroTAdCuwMIr906Mqo-A",
  "name": "New Name",
  "avatar": "https://example.com/new-avatar.jpg",
  "introduction": "This is the updated introduction."
}

**Comment by OngJiaYuan** [comment]
wait sorry correction

http://localhost:8081/account/m2Hq37ggx3O9u10xIFrQ3Myb4br2/update

{
  "name": "New Name",
  "avatar": "https://example.com/new-avatar.jpg",
  "introduction": "This is the updated introduction."
}

**Comment by OngJiaYuan** [comment]
Endpoint to change email and password

http://localhost:8081/account/m2Hq37ggx3O9u10xIFrQ3Myb4br2/update-details

{
  "newEmail": "newemail@example.com",
  "newPassword": "newStrongPassword123!"
}
