### ISSUE TITLE
Encrypt User password and allow user password change

### ISSUE THREAD

**Issue by jonggietechie** [NUS-ISS-Projects/bit-scout-user-service#3]
User password need to be encrypted and there must be an endpoint to verify current password and change existing password.

![image](https://github.com/user-attachments/assets/2de1434c-3af2-4805-bee4-0b4f3edfd9fa)

**Comment by OngJiaYuan** [comment]
The encrypt password should be done on frontend then i decrypt at the back because the firebase auth takes in plain password then will hash before authenticating with the firebase auth

**Comment by OngJiaYuan** [comment]
http://localhost:8081/account/m2Hq37ggx3O9u10xIFrQ3Myb4br2/update-details
{
  "oldPassword": null,
  "newEmail": "new-email@example.com",
  "newPassword": null
}
