### ISSUE TITLE
Endpoint for the get User Details

### ISSUE THREAD

**Issue by jonggietechie** [NUS-ISS-Projects/bit-scout-user-service#4]
Need a endpoint to retrieve user details from the token or user id

Current only retrieve the user id from the token
![image](https://github.com/user-attachments/assets/9ea38f4e-794d-494c-b4b4-de9dde02b394)

**Comment by OngJiaYuan** [comment]
http://localhost:8081/account/user?token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjExYzhiMmRmNGM1NTlkMjhjOWRlNWQ0MTAxNDFiMzBkOWUyYmNlM2IiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYml0LXNjb3V0LTdiYzA4IiwiYXVkIjoiYml0LXNjb3V0LTdiYzA4IiwiYXV0aF90aW1lIjoxNzI0OTQyMTcwLCJ1c2VyX2lkIjoibTJIcTM3Z2d4M085dTEweElGclEzTXliNGJyMiIsInN1YiI6Im0ySHEzN2dneDNPOXUxMHhJRnJRM015YjRicjIiLCJpYXQiOjE3MjQ5NDIxNzAsImV4cCI6MTcyNDk0NTc3MCwiZW1haWwiOiJqb2huZG9lMzJAZXhhbXBsZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiam9obmRvZTMyQGV4YW1wbGUuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.MDqQpG56j5IUVXQ6ncCJOM5WQ3jdPMRU21grjAiKKKLbEplM9nVfrA6rq7L61PBRO9iiQ0YjP6dHzUtK-EvbSJCKsDxOMRM30RS3LsOw5bBgBL14Zj5PqYJjm0IgX2IldtmRCG4ofwBvaGwBHxuX8mRew8TVWf1k6R1sV1lFso4SjPaoTtB3wykHikzDMmLhKZuhodh3WqukKZz4PuZ_HhAcopEyWkNrBxk5f_QaPvXirGBFG-UGS4ftmy5vfwEj-8xciu9dzjmiWGcntZ7AssIWPC3XfFO5idt8G1M32ksNo8awWUCsp7JaVwWHRq0QzONroTAdCuwMIr906Mqo-A

{
    "uid": "m2Hq37ggx3O9u10xIFrQ3Myb4br2",
    "email": "johndoe32@example.com",
    "password": null,
    "name": null,
    "avatar": null,
    "introduction": null
}
